AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda-based File Upload Service

Globals:
  Function:
    Timeout: 10
    Runtime: python3.9

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/auth/
      Handler: lambda_function.lambda_handler
      Events:
        Auth:
          Type: Api
          Properties:
            Path: /auth
            Method: post

  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/upload/
      Handler: lambda_function.lambda_handler
      Events:
        Upload:
          Type: Api
          Properties:
            Path: /upload
            Method: post

  DownloadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/download/
      Handler: lambda_function.lambda_handler
      Events:
        Download:
          Type: Api
          Properties:
            Path: /download
            Method: get

  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/delete/
      Handler: lambda_function.lambda_handler
      Events:
        Delete:
          Type: Api
          Properties:
            Path: /delete
            Method: delete
