name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Adjust with your branch strategy

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies and run tests
      run: |
        pip install -r requirements.txt
        pip install pytest
        python -m pytest tests/
    
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Install SAM CLI
      run: |
        pip install aws-sam-cli
    
    - name: Package and Deploy to AWS Lambda
      run: |
        sam build
        sam package --s3-bucket YOUR_S3_BUCKET_FOR_SAM_ARTIFACTS --output-template-file packaged.yaml
        sam deploy --template-file packaged.yaml --stack-name YOUR_STACK_NAME --capabilities CAPABILITY_IAM --no-confirm-changeset
